#ifndef _SCHEDULER_CONFIG_H_
#define _SCHEDULER_CONFIG_H_


#define SCHEDULER_NB_MAX_EVENT 5
#define SCHEDULER_CLOCK_PRESCALER 8
#define SCHEDULER_MCU_CLOCK 16000 // Khz

#endif // _SCHEDULER_CONFIG_H_
