TARGET = main

# repertoire des modules
AVERSIVE_DIR = ../../../..

SRC  = $(TARGET).c

ASRC = 

CFLAGS += -Wall -Werror

########################################

-include .aversive_conf
include $(AVERSIVE_DIR)/mk/aversive_project.mk

